### ISSUE TITLE
on_press and on_release not executing if one is placed after another

### ISSUE THREAD

**Issue by pshe94** [boppreh/keyboard#152]
Hi, I'm using `on_press `and `on_release` to store any currently pressed keys. Unfortunately, if `on_press` is placed before `on_release`, `on_release` is not being executed. If I switch places of `on_press` with `on_release`, then `on_press` is not being executed.
Because of it, I'm using `hook` as a workaround, in which I'm checking `event_type` and calling proper function.

```
pressed_keys = []

def add_key(key):
    pressed_keys.append(key)
    return

def remove_key(key):
    pressed_keys.remove(key)
    return

keyboard.on_press(add_key)
keyboard.on_release(remove_key)    #This is not being executed
```

Also I have one question: Is there a simpler way of checking in `on_press_key` if other keys are also currently pressed? `modifiers` is always empty.

**Comment by pflaten** [comment]
Hello, 

I was trying to do the same exact thing with `on_press `and `on_release`. It looks like the bug was introduced in a recent update (pip version 0.13.1). I downgraded to version 0.11.0 and that got rid of the bug.

To install version 0.11.0 I used the command: 
`pip install keyboard==0.11.0`

Hope this helps!

**Comment by boppreh** [comment]
I'm taking a look. Version 0.13 revamped a lot of the internals, so this is not too surprising. Still, sorry for the inconvenience.

@pshe94 did 'is_key_pressed' not working for you? Also, list of modifiers currently depends on OS, not all backends are reporting it.

**Comment by pshe94** [comment]
@boppreh Did you mean `is_pressed`? If so, then yes, it works. But it requires to specify which key to check, but I would like to know if any other keys are also pressed. Currently I'm just using `hook` to store all pressed keys (I would use on_press and on_release, but I can't because of this bug).

**Comment by pshe94** [comment]
@boppreh You just made my code a little bit less complicated. Exposing all pressed key is a great idea. Thank you! 👍
Also I have one off-topic question, if you don't mind me asking here. There is no way of combining mouse button presses with keyboard keys? For example hotkey `Ctrl+mouse X2`? I can see that handling mouse is in a separate library, but then I would have to write some kind of wrapper for both of them

**Comment by boppreh** [comment]
@pshe94 I understand the need to combine mouse and keyboard events, and I have that on my roadmap. But I also think it's important to combine hotkeys with arbitrary events/conditions, like active program, window title, or time of day. I'm still thinking on what's the best way to present this flexibility in the API, and how to implement this in a performant way. Suggestions welcome.

**Comment by Magnetization** [comment]
This bug still exists in Version 0.13.3

**Comment by arcadeforge** [comment]
thanks for your awesome work on this project. I made a key 2 joy converter via uinput and experienced that using is_pressed is way to slow. Using the hooks via old version made the trick.

**Comment by samomar** [comment]
Bug still exists in Version: 0.13.4

**Comment by Rasie1** [comment]
Recently I updated my Arch and this bug appeared. Multiple simultaneous hooks (including all functions such as on_press) don't work, I had to copy everything to one hook

**Comment by rayanfer32** [comment]
```py
        keyboard.on_release(trigger_event,suppress=False) 

        PASTE_WORD = "@@pst"
        keyboard.add_word_listener(PASTE_WORD, word_paste ,timeout=1)

        LOGIN_WORD = "@@cit"
        keyboard.add_word_listener(LOGIN_WORD, word_login ,timeout=1)

        LOGINPASS_WORD = "@@citp"
        keyboard.add_word_listener(LOGINPASS_WORD, word_loginpass ,timeout=1)
```
word_listener not getting activated if keyboard.on_release is uncommented 
System: Windows 8.1

**Comment by rayanfer32** [comment]
> ```python
>         keyboard.on_release(trigger_event,suppress=False) 
> 
>         PASTE_WORD = "@@pst"
>         keyboard.add_word_listener(PASTE_WORD, word_paste ,timeout=1)
> 
>         LOGIN_WORD = "@@cit"
>         keyboard.add_word_listener(LOGIN_WORD, word_login ,timeout=1)
> 
>         LOGINPASS_WORD = "@@citp"
>         keyboard.add_word_listener(LOGINPASS_WORD, word_loginpass ,timeout=1)
> ```
> 
> word_listener not getting activated if keyboard.on_release is uncommented
> System: Windows 8.1

Fixed it by placing the `on_release()` after all the `word_listener()`

**Comment by jemiele1** [comment]
Bug still exists in 0.13.5.

When looking at the code for on_press and on_release, I got to thinking that the key event and the "or" operator were not correct, so I made a few changes. In the code below, I have commented out the original return lines and the new ones are directly below the commented lines.

def on_press(callback, suppress=False):
    """
    Invokes `callback` for every KEY_DOWN event. For details see `hook`.
    """
    #return hook(lambda e: e.event_type == KEY_UP or callback(e), suppress=suppress)
    return hook(lambda e: e.event_type == KEY_DOWN and callback(e), suppress=suppress)

def on_release(callback, suppress=False):
    """
    Invokes `callback` for every KEY_UP event. For details see `hook`.
    """
    #return hook(lambda e: e.event_type == KEY_DOWN or callback(e), suppress=suppress)
    return hook(lambda e: e.event_type == KEY_UP and callback(e), suppress=suppress)

For on_press, the "KEY_UP" became "KEY_DOWN" and the "or" become "and".
For on_release, the "KEY_DOWN" became "KEY_UP" and the "or" become "and".

I tried it out on my system and the bug is gone for me!

Anyone want to give this a try? If it works,, on_press_key and on_release_key would need to have a similar change.

**Comment by matteoem** [comment]
as today, this issue is still persisting.

**Comment by cacard** [comment]
why? this is a simple problem, can fix it?

**Comment by Gigabitten** [comment]
@jemiele1 this seems to work for me! thank you greatly.
